image: python:3.6

variables: 
  GIT_STRATEGY: clone

stages:
  - test
  - deploy

before_script:
  - python --version
  - pip list
  
test:
  stage: test
  script:
    - python -m venv env
    - source env/bin/activate
    - python -m pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip list
    - pip install numpy
    - pip install tensorflow
    - pip install h5py
    - python ./test/test.py -v

deploy:
  stage: deploy
  script:
    - cp ./src/models/mnistCNN.h5 ./mnistCNN.h5
  artifacts:
    paths:
      - ./mnistCNN.h5
  